/*
 * LEDMTX_config.c
 *
 *  Created on: Oct 29, 2022
 *      Author: mazen
 */

#include  "../../LIB/STD_TYPES.h"
#include "../../MCAL/GPIO/GPIO_interface.h"


GPIO_Config_t Row_pins[NO_ROWS] = {

/* Port     ,    Pin   ,  Mode    ,  OutputSpeed  , OutputType , InputType , AltFn  */
{GPIO_PORTA  , GPIO_PIN0, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN1, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN2, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN3, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN4, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN5, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN6, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTA  , GPIO_PIN7, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},

};

GPIO_Config_t Col_pins[NO_COLS] = {

/* Port     ,    Pin   ,  Mode    ,  OutputSpeed  , OutputType , InputType , AltFn  */
{GPIO_PORTB  , GPIO_PIN0, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN1, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN5, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN6, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN7, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN8, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN9, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},
{GPIO_PORTB  , GPIO_PIN10, GPIO_OUTPUT, GPIO_2MHZ,  GPIO_PP , GPIO_NOPULL, GPIO_GP},

};





